version: "3.4"


services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 7800:7800
    depends_on:
      - ui
      - api
    command: [nginx-debug, '-g', 'daemon off;']

  ui:
    build: ui
    image: ui
    restart: "no"
    ports:
      - 7778:7778
    depends_on:
      - api

  api:
    build: api
    image: api
    restart: "no"
    volumes:
      - ./api:/app
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env
    
  queue-service:
    build: queue-service
    image: queue-service
    restart: "no"
    volumes:
      - ./queue-service/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - api
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: dab-p2-database-6ddb3376-524f-49d4-a2b2-6fea7ed6ce14
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

